name: check_java_8_compatibility

on:
  push:
  pull_request:

jobs:


  test_linux_java_8:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          git \
          fonts-freefont-otf \
          ghostscript \
          imagemagick

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          ./do_compile.sh && ./do_compile_part2_java_17_needed.sh

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: java-version
        run: java -version

      - name: test
        run: |
          ./do_run.sh

      - name: make image of console output
        run: |
          date > out_with_date.txt
          echo -n 'git hash: ' >> out_with_date.txt
          git rev-parse --verify --short=8 HEAD 2>/dev/null|tr -dc '[A-Fa-f0-9]' 2>/dev/null >> out_with_date.txt
          echo "" >> out_with_date.txt
          ./do_run.sh |grep -e 'sorm.OrmaDatabase' -e 'Runtime' -e 'now_' -e 'Sorma2 \[per ' | grep -v 'appending to orma' >> out_with_date.txt
          cat out_with_date.txt | convert -trim -border 20 -bordercolor black +repage -background black -fill '#00cc00' -pointsize 13 TEXT:- ./java8_console_screen.png

      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "java8_console_screen*.png"

